# Generated by Django 4.1.7 on 2023-03-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_results_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='name',
            new_name='senname',
        ),
    ]
